# Generated by Django 2.0.4 on 2018-04-20 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0002_auto_20180419_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='title',
        ),
    ]
